initial dockerfiles

diff --git a/demo/web/Dockerfile b/demo/web/Dockerfile
--- a/demo/web/Dockerfile
+++ b/demo/web/Dockerfile
@@ -1,24 +1,70 @@
-# 1. stage: build
-FROM node:20.13.1 as builder
+FROM node:22.9.0 AS base
 
-WORKDIR /workspace
+# Install dependencies only when needed
+FROM base AS deps
+
+WORKDIR /app
 
 RUN npm config set https-proxy http://192.168.4.31:10081/
 RUN npm config set proxy http://192.168.4.31:10081/
-COPY package.json package-lock.json ./
-RUN npm install
 
-COPY components.json next-env.d.ts next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json ./
-COPY public ./public
-COPY src ./src
-RUN npm run build
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# 2. stage: runtime ------------------------------------------------------------
-FROM nginx:1.27.0
 
-WORKDIR /opt/app
-EXPOSE 8443
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
 
-COPY nginx.conf /etc/nginx/conf.d/default.conf
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED=1
 
-COPY --from=builder /workspace/out /opt/app/
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 4081
+
+ENV PORT=4081
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
+CMD ["node", "server.js"]
